# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - djangoapp-docker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://dockerapptestregistery.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_b02840d8837b42dfb2e4e346d7b635b4 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_edab9b0e91de4637a12fe38ed3b3b958 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: dockerapptestregistery.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b02840d8837b42dfb2e4e346d7b635b4 }}/dockerapptestregistery.azurecr.io/cicdcontainerrepo:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'djangoapp-docker'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_236f7163e92347c9a28c64f0aa146e35 }}
        images: 'dockerapptestregistery.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b02840d8837b42dfb2e4e346d7b635b4 }}/dockerapptestregistery.azurecr.io/cicdcontainerrepo:${{ github.sha }}'